#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# deploy.sh — Build & launch the Secure Bookmark Manager
# =============================================================================
# 1. Check Docker & Docker Compose versions
# 2. Create .env with a random SECRET_KEY if it doesn't exist
# 3. Initialise the SQLite schema locally (so the volume starts with tables)
# 4. Run docker compose up --build
# =============================================================================

COMPOSE_FILE="docker-compose.yml"
DATA_DIR="./data"                  # local mirror of the container's /app/data
ENV_FILE=".env"

# --------------- colours -----------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# =============================================================================
# 1. Docker & Docker Compose version checks
# =============================================================================
command -v docker >/dev/null 2>&1 || error "Docker is not installed or not in PATH."

DOCKER_VERSION=$(docker --version)
info "Docker version: $DOCKER_VERSION"

# docker compose (v2 plugin) or docker-compose (standalone)
if docker compose version >/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
    COMPOSE_VERSION=$(docker compose version --short)
elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE_CMD="docker-compose"
    COMPOSE_VERSION=$(docker-compose version --short)
else
    error "Docker Compose is not installed. Install the Docker Compose plugin or standalone binary."
fi

info "Docker Compose version: $COMPOSE_VERSION"

# =============================================================================
# 2. Create .env if missing
# =============================================================================
if [ ! -f "$ENV_FILE" ]; then
    warn ".env file not found — generating one with a random SECRET_KEY."

    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")

    cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Flask Secret Key
SECRET_KEY=${SECRET_KEY}

# Database path (must match Dockerfile /app/data mount)
BOOKMARK_DB_PATH=/app/data/bookmarks.db

# Debug (false in production)
FLASK_DEBUG=false
EOF

    info "Created $ENV_FILE — review it and commit the file (but never commit real secrets!)."
else
    info ".env file already exists — skipping creation."
fi

# =============================================================================
# 3. Initialise SQLite schema locally
#    The container's /app/data is a Docker volume.  By seeding the local ./data
#    directory we ensure the volume starts with the correct schema even on a
#    brand-new machine.
# =============================================================================
mkdir -p "$DATA_DIR"

info "Initialising SQLite database in $DATA_DIR …"

python3 - "$DATA_DIR" <<'PYEOF'
import sqlite3, sys, os

data_dir = sys.argv[1]
os.makedirs(data_dir, exist_ok=True)

# ── bookmarks.db (consolidated) ──────────────────────────────────────────────
bk_path = os.path.join(data_dir, "bookmarks.db")
conn = sqlite3.connect(bk_path)

# Users table
conn.execute("""
    CREATE TABLE IF NOT EXISTS users (
        id                INTEGER   PRIMARY KEY AUTOINCREMENT,
        username          TEXT      UNIQUE NOT NULL,
        password_hash     TEXT      NOT NULL,
        role              TEXT      NOT NULL DEFAULT 'user',
        two_factor_secret TEXT      DEFAULT NULL,
        created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
""")
# Migrations — add columns that may be missing from older installs
_user_migrations = [
    ("two_factor_secret", "TEXT DEFAULT NULL"),
    ("role", "TEXT NOT NULL DEFAULT 'user'"),
]
for col, defn in _user_migrations:
    try:
        conn.execute(f"ALTER TABLE users ADD COLUMN {col} {defn}")
    except sqlite3.OperationalError:
        pass

# Bookmarks table
conn.execute("""
    CREATE TABLE IF NOT EXISTS bookmarks (
        id          INTEGER   PRIMARY KEY AUTOINCREMENT,
        user_id     INTEGER   NOT NULL,
        title       TEXT      NOT NULL,
        url         TEXT      NOT NULL,
        description TEXT      DEFAULT NULL,
        folder      TEXT      NOT NULL DEFAULT 'Uncategorized',
        tags        TEXT      NOT NULL DEFAULT '',
        created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
""")
# Migrations — add columns that may be missing from older installs
_migrations = [
    ("description",       "TEXT DEFAULT NULL"),
    ("updated_at",        "TIMESTAMP DEFAULT NULL"),
    ("last_accessed_at",  "TIMESTAMP DEFAULT NULL"),
    ("status",            "TEXT DEFAULT 'active'"),
    ("last_validated_at", "TIMESTAMP DEFAULT NULL"),
]
for col, defn in _migrations:
    try:
        conn.execute(f"ALTER TABLE bookmarks ADD COLUMN {col} {defn}")
    except sqlite3.OperationalError:
        pass

# Category metadata table
conn.execute("""
    CREATE TABLE IF NOT EXISTS category_meta (
        id            INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id       INTEGER NOT NULL,
        category_name TEXT    NOT NULL,
        emoji         TEXT    NOT NULL DEFAULT '📁',
        UNIQUE(user_id, category_name)
    )
""")
conn.commit()
conn.close()
print(f"  ✓ {bk_path}")
PYEOF

info "Schema initialisation complete."

# =============================================================================
# 4. Build & start
# =============================================================================
info "Building and starting containers …"
$COMPOSE_CMD --env-file "$ENV_FILE" up --build -d

info "Waiting for the web app to become healthy …"
# Give gunicorn a few seconds to boot
sleep 3

if curl -sf http://localhost:5000 >/dev/null 2>&1; then
    info "✅  Application is up and running at http://localhost:5000"
else
    warn "Application may still be starting — check with: $COMPOSE_CMD logs -f web_app"
fi
